### ISSUE TITLE
Customize interactive labeler

### ISSUE THREAD

**Issue by khursani8** [jina-ai/finetuner#182]
Currently interactive labeler only support Image and Text, is there some kind of middle layer API or similar so that I can modify to allow Audio interactive labeling?

I want to label similar speaker based on audio clip.

Thanks

**Comment by Roshanjossey** [comment]
Hi @khursani8, thank you for your feature request. We'll work on this.

**Comment by Roshanjossey** [comment]
Hi @khursani8, we've released a patch version that supports interactive labelling for Audio https://github.com/jina-ai/finetuner/releases/tag/v0.1.5

If you want to extend it further and use other data types, you can check the changes in this PR: https://github.com/jina-ai/finetuner/pull/185/files

Please let us know if you have some feedback :)

**Comment by khursani8** [comment]
Ok thanks, will take a look
