### ISSUE TITLE
Create Evaluation Example

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/finetuner#193]
We want an evaluation pipeline, that measures the quality

- independent of current building blocks
- input: model, data, potentially catalog
- output some evaluation metric like NDCG, MRR
- accompanied by a dataset (e.g. totally looky like, CELEBA)
- give the tuner 5/10/15 minutes

**Comment by tadejsv** [comment]
Two cars datasets that we could use:
- http://ai.stanford.edu/~jkrause/cars/car_dataset.html
- http://mmlab.ie.cuhk.edu.hk/datasets/comp_cars/index.html

**Comment by tadejsv** [comment]
Another one:
- https://qmul-vric.github.io/

**Comment by maximilianwerk** [comment]
Done for the current refactoring
