### ISSUE TITLE
Tailor vision transformer (DINO)

### ISSUE THREAD

**Issue by jmorese** [jina-ai/finetuner#199]
Hi there! 
I am trying to tailor a vision transformer (DINO) adding a projection layer on top of the whole transformer arquitecture.

When I run ` finetuner.tailor.to_embedding_model(model,output_dim=100, input_size=(3, 224, 224))`  I get the following error.

![image](https://user-images.githubusercontent.com/80267926/141760026-423bb83f-bf28-4db7-bdf9-5b8dcc6a15b6.png)

I get the model from `vits8 = torch.hub.load('facebookresearch/dino:main', 'dino_vits8')`

code snippet to reproduce error
```
import torch
import finetuner

vits8 = torch.hub.load('facebookresearch/dino:main', 'dino_vits8')

finetuner.tailor.to_embedding_model(vits8,output_dim=100, input_size=(3, 224, 224))
```

**Comment by bwanglzu** [comment]
hi @jmorese you're right, i'm sorry but the current tailor is not tested on transformers/vision transformers and relative new architectures. This is in development.

**Comment by CatStark** [comment]
Hi @jmorese I will close this issue after Bo's response. But please feel free to raise an issue again if you feel this isn't solved :)
