### ISSUE TITLE
unsupervised finetuning on text

### ISSUE THREAD

**Issue by myntoralex** [jina-ai/finetuner#287]
I have a search use case where I need to match text to text, fine tune the matches, and save the documents in Postgres. The original flow uses a sentence-transformer model, namely 'paraphrase-albert-small-v2' and the HNSWPostgresIndexer. I might have a document with text "Who founded the company?" and would need to be retrieved with the input "Who made you?" I don't see a good walkthrough for this, though I assume something similar to the helloworld chatbot finetuner is in order.

**Comment by tadejsv** [comment]
Hey @myntoralex, can you describe your use case a bit more - namely, I would like to know how does your training dataset look like. Do you have many labeled examples? Is there any difference between the "answers" and "questions" in your dataset? 

This will help me answer your question better

**Comment by bwanglzu** [comment]
will close, this will be implemented later
