### ISSUE TITLE
Make release based on git tag, source version from `setup.cfg`

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/finetuner#291]
I want to make the release action driven by git events (and not the other way around). Namely:
- when you create a tag on the main branch, a release is triggered
- the version of the package, along with the rest of metadata, would be set in `setup.cfg` - the modern way that `setuptools` recommends. This file can also host `flake8` configuration, with the rest being in `pyproject.toml`
- `setup.py` no longer needed

Release procedure would then consist of two steps:
- create a tag, corresponding to version [release happens automatically]. Here a step in the release action will check whether tag equals version in `setup.cfg`
- bump the version in `setup.cfg`

Benefits of this approach are that it is much more transparent, reacts to events instead of creating them, and consequently does not require any writing to the repository by the bot. It's also a more or less established way of publishing python packages, see [this](https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/) for example

**Comment by JoanFM** [comment]
In the link provided, is not clear that `setup.py` is to be removed right?

**Comment by tadejsv** [comment]
The link demonstrates the use of git tag-based release

**Comment by JoanFM** [comment]
and is there a link showing setuptools recommends not to use `steup.py`?

**Comment by tadejsv** [comment]
Here, for example: https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata

> Static metadata (setup.cfg) should be preferred. Dynamic metadata (setup.py) should be used only as an escape hatch when absolutely necessary. setup.py used to be required, but can be omitted with newer versions of setuptools and pip.
