### ISSUE TITLE
Explore text self-supervised learning techniques

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/finetuner#298]
Try out
- masking/augmentation
- established techniques (TS-DAE, SimCSE)

Use a more-or-less standardized dataset for text similarity (e.g. from benchmarks used in the papers), and try to compare results. Not necessary to use finetuner for now, as we are exploring techniques to integrate into fintuner later

**Comment by azayz** [comment]
SimCSE: stands for simple contrastive learning for sentence embeddings 

proposes two ways of improving sentence embeddings using contrastive learning. 

1. Using Unsupervised learning: Do two forward passes through a dropout, use the slightly different embeddings as positives and the rest of the sentence embeddings in that mini batch as negatives. 
2. Using supervised learning:

**Comment by azayz** [comment]
https://docs.google.com/presentation/d/1GhYggjsMg-7YvEFyD-1a9-jOxSY26IiI/edit?usp=sharing&ouid=116224065734438057464&rtpof=true&sd=true
