### ISSUE TITLE
Progress bar not visible when using .fit()

### ISSUE THREAD

**Issue by makram93** [jina-ai/finetuner#301]
When I run the below script on my PyCharm, I do not see progress bar, however when I terminate the process or when training completes then the progress bar becomes visible.

```python
import finetuner
import torch
from finetuner.toydata import generate_fashion

model = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.Linear(
        in_features=28 * 28,
        out_features=128,
    ),
    torch.nn.ReLU(),
    torch.nn.Linear(in_features=128, out_features=32),
)

# Train
finetuner.fit(
    model,
    train_data=generate_fashion(num_total=20000),
    eval_data=generate_fashion(is_testset=True, num_total=100),
    epochs=20,
    batch_size=16,
    num_items_per_class=2,
)
```
![ezgif com-gif-maker](https://user-images.githubusercontent.com/6537525/147085933-724f0b29-8766-4f65-b941-a174a5ed820b.gif)

**Comment by gmastrapas** [comment]
I think you need to check the box 'Emulate terminal in console'

**Comment by makram93** [comment]
Ah, yes it shows now. Thanks! 👍
