### ISSUE TITLE
Add projection head option to Tuner

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/finetuner#315]
`ProjectionHead`, first proposed in SimCLR paper, is adding a 2-3 layer MLP on top of the embedding model, this trick is able to bootstrap the representation learning. This has became a common practice in contrastive representation learning.

This PR will:
1. create a simple MLP head in tuner, if `DataSet` is `UnlabaledDataset`, attach the projection head on top of the model.
2. chop the projection head once training is finished, and leave out the embedding model.
3. add tests.

**Comment by bwanglzu** [comment]
note: after discussion, we'll add it into Tailor as SimCLRv2 use this MLP for finetunning without removing it.
