### ISSUE TITLE
labeler: browser opens before ready

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/finetuner#346]
When using the labeler, the browser opens and just shows white screen while the script is working in the background. Sometimes even when script has finished working, need to reload browser window to get the UI

Finetuner 0.3.0

**Comment by alexcg1** [comment]
Code:
```python
finetuner.fit(
    model,
    train_data=docs,
    interactive=True,
    to_embedding_model=True,
    freeze=False,
    input_size=(3, 80, 60),
)
```

**Comment by bwanglzu** [comment]
update: the labeler has been removed from finetuner
