### ISSUE TITLE
Tuner needs to read `options` parameter from config

### ISSUE THREAD

**Issue by violenil** [jina-ai/finetuner#417]
In the `config` we need to be able to specify an `options` parameter as follows:

```
{
  "model": ...
  "options": {
    "word_embedding_dim": 768,
    "pooling": "mean"
  },
  "freeze": false,
  "multi_modal" false,
  ...
```

Such that `tuner.fit` can take an additional argument like `model_options`.

**Comment by gmastrapas** [comment]
The options field is in the model field right?

**Comment by violenil** [comment]
> The options field is in the model field right?

True!
