### ISSUE TITLE
Support `query_data` and `index_data` in tuner

### ISSUE THREAD

**Issue by violenil** [jina-ai/finetuner#418]
Currently there is only support the use of one evaluation `DocumentArray` in `tuner.fit`. However, it is quite customary to use a set of queries (`query_data`) and a set of indexes (`index_data`) as evaluation data for the `Evaluator`, ie. these are two separate `DocumentArray`s. This option should be supported in finetuner.

**Comment by gmastrapas** [comment]
User will be able to use the evaluation callback which supports index and query data. See https://github.com/jina-ai/finetuner/pull/415
