### ISSUE TITLE
Impossible to login in notebook, also impossible to fit

### ISSUE THREAD

**Issue by louis030195** [jina-ai/finetuner#503]
```py
import finetuner
finetuner.login()
```

>asyncio.run() cannot be called from a running event loop

```py
import finetuner

run = finetuner.fit(model="msmarco-distilbert-base-v3", train_data=train_da)
```

>'NoneType' object has no attribute 'create_run'

`MacOS Monterey M1 12.5`
`finetuner==0.5.1`
`Python 3.8.13`

**Comment by gmastrapas** [comment]
Hey @louis030195 thanks for bringing this up! Are you working on google colab? You can patch asyncio to allow nested event loops using this https://github.com/erdewit/nest_asyncio 

Once login is working, fit will also work

**Comment by bwanglzu** [comment]
thanks for the question, i'll close it for now, feel free to open a new one if you encounter other issues!

**Comment by vonrafael** [comment]
This issue still persists.
Here I'm running this in my kaggle and I got this

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_23/1800214748.py in <module>
      4     learning_rate=1e-5,
      5     loss='CLIPLoss',
----> 6     device="cuda",
      7 )

/opt/conda/lib/python3.7/site-packages/hubble/__init__.py in arg_wrapper(*args, **kwargs)
     46         try:
     47             Client(jsonify=True).get_user_info()
---> 48             return func(*args, **kwargs)
     49         except AuthenticationRequiredError:
     50             raise AuthenticationRequiredError(

/opt/conda/lib/python3.7/site-packages/finetuner/__init__.py in fit(model, train_data, eval_data, run_name, description, experiment_name, model_options, loss, miner, miner_options, optimizer, optimizer_options, learning_rate, epochs, batch_size, callbacks, scheduler_step, freeze, output_dim, cpu, device, num_workers, to_onnx, csv_options, public, num_items_per_class)
    241         csv_options=csv_options,
    242         public=public,
--> 243         num_items_per_class=num_items_per_class,
    244     )
    245 

/opt/conda/lib/python3.7/site-packages/hubble/__init__.py in arg_wrapper(*args, **kwargs)
     46         try:
     47             Client(jsonify=True).get_user_info()
---> 48             return func(*args, **kwargs)
     49         except AuthenticationRequiredError:
     50             raise AuthenticationRequiredError(

/opt/conda/lib/python3.7/site-packages/finetuner/finetuner.py in create_run(self, model, train_data, eval_data, run_name, description, experiment_name, model_options, loss, miner, miner_options, optimizer, optimizer_options, learning_rate, epochs, batch_size, callbacks, scheduler_step, freeze, output_dim, cpu, device, num_workers, to_onnx, csv_options, public, num_items_per_class)
    178         else:
    179             experiment = self.get_experiment(name=experiment_name)
--> 180         return experiment.create_run(
    181             model=model,
    182             train_data=train_data,

AttributeError: 'NoneType' object has no attribute 'create_run'
