### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by RaiAmanRai** [jina-ai/finetuner#508]
Hi @ZiniuYu  , I am trying to log in to [Finetuner](https://finetuner.jina.ai/) using finetuner.login() command. 

Although, it displays `🔐 Successfully login to Jina Ecosystem!` on the terminal and get a login successful message on the browser, soon after that I get the below error on the terminal.

`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/usr/local/lib/python3.8/dist-packages/finetuner/__init__.py", line 31, in login`
  `  ft.login()`
  `File "/usr/local/lib/python3.8/dist-packages/finetuner/finetuner.py", line 29, in login`
  ` self._default_experiment = self._get_default_experiment()`
  `File "/usr/local/lib/python3.8/dist-packages/finetuner/finetuner.py", line 43, in _get_default_experiment`
  `  return self.create_experiment(name=experiment_name)`
  `File "/usr/local/lib/python3.8/dist-packages/finetuner/finetuner.py", line 54, in create_experiment`
  ` experiment_info = self._client.create_experiment(name=name)`
  `File "/usr/local/lib/python3.8/dist-packages/finetuner/client/client.py", line 37, in create_experiment`
  `  return self._handle_request(`
  `File "/usr/local/lib/python3.8/dist-packages/finetuner/client/base.py", line 77, in _handle_request`
  `  raise FinetunerServerError(`
`finetuner.exception.FinetunerServerError: Unprocessable Entity (422): [{'loc': ['body', 'name'], 'msg': 'Use a non-empty name for` `your experiment.', 'type': 'value_error'}]`

Any help on this?

**Comment by bwanglzu** [comment]
hi @RaiAmanRai thanks for reporting this, we're looking into the logs and will get back to you soon

**Comment by RaiAmanRai** [comment]
Yeah sure @bwanglzu , i am trying to run it inside a docker and at the root of it  `clip:/#`.
Here, clip is the docker name.

**Comment by bwanglzu** [comment]
thanks! let me try to reproduce

**Comment by bwanglzu** [comment]
indeed, we have never tested run finetuner in a docker image, i can reproduce the error:

minimum to reproduce:
1. create docker file:
```docker
FROM python:3.9

RUN pip install -U finetuner

ENTRYPOINT ["python"]
```

2. build docker image: `docker build -f Dockerfile -t test:latest .`
3. `docker container create -i -t --name mycontainer test:latest`
4. `docker container start --attach -i mycontainer`
5. in python shell:
```python
>>> import finetuner
>>> finetuner.login()
👉 Your browser is going to open the login page, if not please open the following link: 
https://jina-ai.us.auth0.com/authorize?...
🔐 Successfully login to Jina AI!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/finetuner/__init__.py", line 31, in login
    ft.login()
  File "/usr/local/lib/python3.9/site-packages/finetuner/finetuner.py", line 29, in login
    self._default_experiment = self._get_default_experiment()
  File "/usr/local/lib/python3.9/site-packages/finetuner/finetuner.py", line 43, in _get_default_experiment
    return self.create_experiment(name=experiment_name)
  File "/usr/local/lib/python3.9/site-packages/finetuner/finetuner.py", line 54, in create_experiment
    experiment_info = self._client.create_experiment(name=name)
  File "/usr/local/lib/python3.9/site-packages/finetuner/client/client.py", line 37, in create_experiment
    return self._handle_request(
  File "/usr/local/lib/python3.9/site-packages/finetuner/client/base.py", line 77, in _handle_request
    raise FinetunerServerError(
finetuner.exception.FinetunerServerError: Unprocessable Entity (422): [{'loc': ['body', 'name'], 'msg': 'Use a non-empty name for your experiment.', 'type': 'value_error'}]
>>> 
```

**Comment by bwanglzu** [comment]
in the mean time, @RaiAmanRai can you run it outside a docker container?

**Comment by RaiAmanRai** [comment]
thanks, atleast now I know this wasn't just for me. 

Few more findings, I suspected that maybe it's the case where the docker requires external ports to be enabled, but I tested it out on another docker without any port mapping and it ran fine. 

So I couldn't narrow out this problem source. Let me know if you know more inputs.

**Comment by RaiAmanRai** [comment]
update :  My colleague tried to run the finetuner **inside** the same docker mentioned before, and was able to successfully run the commands and finetuning process.

Only difference this time, is the email he used for login. I tried to use a different one of mine, and got the same error again. 
Can't really be sure if it's any authorization error.

**Comment by gmastrapas** [comment]
Hey @RaiAmanRai , finetuner initially creates a default experiment named after the directory you are working on. I think you mentioned you are working on `/`. So this might cause an empty experiment name. Can you try a different directory inside the container? Say `/home` or `/usr/src/app`?

**Comment by RaiAmanRai** [comment]
@gmastrapas you saved the day. Finetuner works now, ig the error makes more sense now.

Again thanks a lot. cheers!
