### ISSUE TITLE
Blogpost about hybridsearch

### ISSUE THREAD

**Issue by CatStark** [jina-ai/finetuner#557]

**Comment by CatStark** [comment]
We encounter another problem documented [here](https://github.com/jina-ai/finetuner-core/issues/326)

**Comment by guenthermi** [comment]
The colab notebook: https://colab.research.google.com/drive/1oaFQHGH8RVt8Nw7o7Rd1aQyT34O0rc19?usp=sharing
the template for the blogpost: https://docs.google.com/document/d/1NXTOoWsC2G6wWLJOEamW91VaMHW_vFQWpU7G69y6zsc/edit?usp=sharing

**Comment by guenthermi** [comment]
The first draft of the blog post is finished: https://www.notion.so/Finetuner-and-Hybrid-Search-ec1f67e1229e45f594bd866627620d1a

**Comment by CatStark** [comment]
New version: https://www.notion.so/Hybrid-Multi-Modal-Search-using-Jina-AI-eaa9fcc259bb4aadac22b5ab8e997204

**Comment by guenthermi** [comment]
We will try out a new dataset because the finetuning does not deliver a large improvement when trained on such a small dataset in an unsupervised manner. We might also try out how good it will work when we train the models in a supervised manner.

**Comment by guenthermi** [comment]
For electronics data:  https://www.notion.so/Hybrid-Search-Electronics-Dataset-98c1675f56e14456a0884bdd7631e19c
