### ISSUE TITLE
blog post about clip benchmark

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/finetuner#565]
LAION release CLIP benchmark: https://github.com/LAION-AI/CLIP_benchmark to evaluate zero-shot retrieval ability, we want to build on top of it and examine how fine-tuned  model could help

**Comment by bwanglzu** [comment]
https://www.notion.so/We-fine-tuned-9-CLIP-models-for-search-here-are-the-results-2e172866ee4a4e36922015ac2e5c83ab

**Comment by CatStark** [comment]
We aim to finish it by Oct 26
