### ISSUE TITLE
Show a progress bar during the execution in the finetuner.encode function

### ISSUE THREAD

**Issue by guenthermi** [jina-ai/finetuner#572]
Encoding a large document array could take a while. We can add an optional argument show_progress to the function and allow the function to show a progress bar which visualizes the number of batches processed.

**Comment by bwanglzu** [comment]
supported in docarray, let's bump and upgrade: https://github.com/jina-ai/docarray/pull/628

**Comment by bwanglzu** [comment]
merged in #586
