### ISSUE TITLE
Support 4 new CLIP models trained on LAION2B

### ISSUE THREAD

**Issue by ZiniuYu** [jina-ai/finetuner#574]
Laion AI recently released 4 new CLIP models trained on LAION2B https://laion.ai/blog/large-openclip/
These models are supported in latest [open clip module](https://github.com/mlfoundations/open_clip) (`open_clip_torch >= 2.0.0`)
It would be nice to have these models supported in finetuner.

**Comment by bwanglzu** [comment]
won't support since we're working reduce the number of models to support, in short: we'll only support 2 clip models: base and large
