### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by jjohn485** [jina-ai/finetuner#591]
Hello, you all have done a great job with Jina and I'm really excited to get started with it, particularly with your finetuner.

I am trying to log in to Jina through the login portal using my email and password but when it redirects me to cloud.jina.ai, the login button is still active at the top indicating that it never logged me in. I click the login button and it brings me back to the login portal and restarts the loop, never actually letting me login. 

Please help. Thank you!

**Comment by bwanglzu** [comment]
hi @jjohn485 thanks for reporting, we have fixed the google colab, hopefully it works for you know, I'll close this PR and feel free to raise a new one if you have further questions!
