### ISSUE TITLE
Add before/after comparisons at the end of notebooks

### ISSUE THREAD

**Issue by LMMilliken** [jina-ai/finetuner#613]
Each of our notebooks currently describe the process of finetuning a model, but don't provide any direct comparisons of the search results between the zero-shot and the finetuned models.
A before/after section should be added to each notebook, they should show example queries and the top result(s) returned by both the zero-shot and the pre-trained model

**Comment by LMMilliken** [comment]
Currently, the before/after examples in the image-image notebook is not very good, especially compared to a similar example in the documentation of finetuner version 0.4.1. One identified difference between 0.4.1 and current versions is that the preprocessing function now resizes the images, whereas it did not before. Also, the model used to get the before/after examples in the current notebook did not have the correct tuning parameters.

**Comment by LMMilliken** [comment]
currently working on improving finetuning results by not resizing images that are already the correct size. Once that is done I will collect another set of before/after examples, hopefully with better results

**Comment by LMMilliken** [comment]
Better before/after comparisons have been added and the performance of the model using the finetunung parameters in the notebook have been validated. Changes made to finetuner-client in https://github.com/jina-ai/finetuner-api/issues/204 are causing the client tests to fail, so other changes in client need to be made before merging

**Comment by guenthermi** [comment]
An example 3D point cloud:
![Screenshot from 2022-12-15 10-56-23](https://user-images.githubusercontent.com/6599259/208113813-bcf498d9-edf7-4496-a087-03bb783f3b70.png)

**Comment by guenthermi** [comment]
clip-example-pt
![clip-example-pt](https://user-images.githubusercontent.com/6599259/212634395-6f336d39-cda7-425d-80a2-10facae3b824.png)

clip-example-ft
![clip-example-ft](https://user-images.githubusercontent.com/6599259/212634112-a44c6c4c-2cc1-4dfb-8e29-0d02b2d6b95c.png)
image-image-triplets-good
![image-image-triplets-good](https://user-images.githubusercontent.com/6599259/212634591-03bd93dc-900f-47c5-8ada-77cf1d4f9fe6.png)
image-image-triplets-bad
![image-image-triplets-bad](https://user-images.githubusercontent.com/6599259/212634649-370b643b-63ad-4d46-8a16-bc4988265568.png)
WandB-mclip
![WandB-mclip](https://user-images.githubusercontent.com/6599259/212645881-20071aba-8643-4878-bc53-97eb6f766bf0.png)
