### ISSUE TITLE
(Bug) Falling when login using PAT

### ISSUE THREAD

**Issue by CatStark** [jina-ai/finetuner#626]
**Description:**
[Colab](https://colab.research.google.com/drive/1Ui3Gw3ZL785I7AuzlHv3I0-jTvFFxJ4_?usp=sharing#scrollTo=j_MxAW9E-ddZ) is failling when authenticating via PAT. It works fine with browser log in. 

It's maybe a Hubble issue?

![Screenshot 2022-11-29 at 15 35 40](https://user-images.githubusercontent.com/3002344/204563251-9fcf1350-ab18-4d11-b17f-68807701ac45.png)

**Comment by LMMilliken** [comment]
This is an issue with the current version of hubble that finetuner is using. For the time being, importing this branch of hubble will fix it, and we will bump our hubble version in the next release:
`!pip install git+https://github.com/jina-ai/jina-hubble-sdk.git@fix-post-success-type`

**Comment by bwanglzu** [comment]
should have been fixed since now we have the latest sdk
