### ISSUE TITLE
Add support for CSVs based on binary relevance judgement

### ISSUE THREAD

**Issue by LMMilliken** [jina-ai/finetuner#632]
Currently, training/evaluation data for finetuning can only be passed as CSV files if the rows either consist of pairs of similar items, or an item followed by a label. CSVs should also be able to be passed in the following format:
```
query, document, relevancy
"my example query", "a candidate retrieval results", 1
"my example query", "another candidate retrieval result", 0
...
```

**Comment by guenthermi** [comment]
With the triplet margin loss, we can not support pure negatives which have no positive document. So having 0 relevance might not make sense. At the moment, we support users to create a dataset of pairs:

```
query, document, relevancy
"my example query", "a candidate retrieval results", 1
"my example query", "another candidate retrieval result", 1
...
```

This creates a dataset with 4 documents:

```
query, label
"my example query", 1
"a candidate retrieval results", 1
"my example query", 2
"another candidate retrieval result", 2
```

However it might be better to create a dataset without duplicating the queries,  and less labels:
```
query, label
"my example query", 1
"a candidate retrieval results", 1
"another candidate retrieval result", 1
```

The goal of this ticket should be to first check which method works better and support the second method in the client and the API

**Comment by matousek-martin** [comment]
Experiment on the xmarket data:

  | Dataset A | Dataset B
-- | -- | --
MRR | 0.5520231598445182 | 0.5519900708940532



Dataset A
```
query, label
"my example query", 1
"a candidate retrieval results", 1
"my example query", 2
"another candidate retrieval result", 2
```

Dataset B
```
query, label
"my example query", 1
"a candidate retrieval results", 1
"another candidate retrieval result", 1
```
