### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 

### ISSUE THREAD

**Issue by leila000** [jina-ai/finetuner#660]
I logged in successfully in jina and import finetune as well

when i call below command
`finetuner.create_experiment(name='test')`

it shows

> [/usr/local/lib/python3.8/dist-packages/finetuner/finetuner.py](https://localhost:8080/#) in create_experiment(self, name)
     64         if not name:
     65             name = self._get_cwd()
---> 66         experiment_info = self._client.create_experiment(name=name)
     67         return Experiment(
     68             client=self._client,

AttributeError: 'NoneType' object has no attribute 'create_experiment'

**Comment by gmastrapas** [comment]
Hi @leila000 thanks for the feedback! Which finetuner version are you using?

**Comment by leila000** [comment]
@gmastrapas Hi I'm currently using 0.6.7 
and i installed it by using 'pip install "finetuner[full]"'

**Comment by guenthermi** [comment]
you need to call `finetuner.login()` before you can create an experiment. Sorry that the error message is so confusing. We will improve this.

**Comment by guenthermi** [comment]
Did you execute this in a jupyter notebook?
Maybe something went wrong with the login and you need to click on the link if you see this:
![147A8319-7BFA-4D0C-9B1C-661DAF6B040E (1)](https://user-images.githubusercontent.com/6599259/213179647-678b8345-8881-4027-a093-656b6a3027b8.png)

**Comment by leila000** [comment]
well.. 
I think i login successfully 

![jina](https://user-images.githubusercontent.com/26996413/213324865-5a5c8b39-86a9-49f3-8e9c-e1aedd5b0273.PNG)
