### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_run'

### ISSUE THREAD

**Issue by vonrafael** [jina-ai/finetuner#707]
This issue still persists.
Here I'm running this in my kaggle and I got this

AttributeError Traceback (most recent call last)
/tmp/ipykernel_23/1800214748.py in
4 learning_rate=1e-5,
5 loss='CLIPLoss',
----> 6 device="cuda",
7 )

/opt/conda/lib/python3.7/site-packages/hubble/init.py in arg_wrapper(*args, **kwargs)
46 try:
47 Client(jsonify=True).get_user_info()
---> 48 return func(*args, **kwargs)
49 except AuthenticationRequiredError:
50 raise AuthenticationRequiredError(

/opt/conda/lib/python3.7/site-packages/finetuner/init.py in fit(model, train_data, eval_data, run_name, description, experiment_name, model_options, loss, miner, miner_options, optimizer, optimizer_options, learning_rate, epochs, batch_size, callbacks, scheduler_step, freeze, output_dim, cpu, device, num_workers, to_onnx, csv_options, public, num_items_per_class)
241 csv_options=csv_options,
242 public=public,
--> 243 num_items_per_class=num_items_per_class,
244 )
245

/opt/conda/lib/python3.7/site-packages/hubble/init.py in arg_wrapper(*args, **kwargs)
46 try:
47 Client(jsonify=True).get_user_info()
---> 48 return func(*args, **kwargs)
49 except AuthenticationRequiredError:
50 raise AuthenticationRequiredError(

/opt/conda/lib/python3.7/site-packages/finetuner/finetuner.py in create_run(self, model, train_data, eval_data, run_name, description, experiment_name, model_options, loss, miner, miner_options, optimizer, optimizer_options, learning_rate, epochs, batch_size, callbacks, scheduler_step, freeze, output_dim, cpu, device, num_workers, to_onnx, csv_options, public, num_items_per_class)
178 else:
179 experiment = self.get_experiment(name=experiment_name)
--> 180 return experiment.create_run(
181 model=model,
182 train_data=train_data,

AttributeError: 'NoneType' object has no attribute 'create_run'

**Comment by LMMilliken** [comment]
Typically this error occurs when logging in is not done properly, try including the line `finetuner.login(force=True)` before you call `fintuner.fit`.
