### ISSUE TITLE
(Docs - Concepts) Describe different login options

### ISSUE THREAD

**Issue by guenthermi** [jina-ai/finetuner#724]
Describe how to login with all the options (probably only force) like [here](https://finetuner.jina.ai/walkthrough/login/) but also mention a bit more details, e.g. what is a auth token, a user id, the prefixes in hubble (or link to pages which explain this) and provide a trouble shooting section for common errors, e.g., if login fails in a notebook try to use force.

**Comment by bwanglzu** [comment]
![namespace1](https://user-images.githubusercontent.com/9794489/233982646-9476b885-89a9-45e4-9dd7-eea9127afb4c.jpeg)
![namespace2](https://user-images.githubusercontent.com/9794489/233982661-25a840a0-6812-4752-96b2-6c692dbf0ead.jpeg)
